/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Button: typeof import('@material-ui/core')['Button']
  const CardView: typeof import('@material-ui/core')['Card']
  const Container: typeof import('@material-ui/core')['Container']
  const Dialog: typeof import('@material-ui/core')['Dialog']
  const DialogContent: typeof import('@material-ui/core')['DialogContent']
  const Grid: typeof import('@material-ui/core')['Grid']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
