/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Box: typeof import('@mui/material')['Box']
  const Button: typeof import('@mui/material')['Button']
  const CardActions: typeof import('@mui/material')['CardActions']
  const CardContent: typeof import('@mui/material')['CardContent']
  const CardView: typeof import('@mui/material')['Card']
  const Container: typeof import('@mui/material')['Container']
  const Dialog: typeof import('@mui/material')['Dialog']
  const DialogContent: typeof import('@mui/material')['DialogContent']
  const Grid: typeof import('@mui/material')['Grid']
  const TextField: typeof import('@mui/material')['TextField']
  const Typography: typeof import('@mui/material')['Typography']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}
